apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false
    artifacts:
        -   image: bidego/educacion-digital-edi
            context: edi
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
                '**/*.tsx': .
                '**/*.css': .
                '**/*.html': .
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yml
