apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false
    artifacts:
        -   image: bidego/educacion-digital-edi
            context: edi
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
                '**/*.tsx': .
                '**/*.css': .
                '**/*.html': .
        -   image: bidego/educacion-digital-server
            context: server
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
        -   image: bidego/educacion-digital-worker
            context: worker
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yml
            - k8s/server-deployment.yml
            - k8s/worker-deployment.yml
            - k8s/client-cluster-ip-service.yml
            - k8s/server-cluster-ip-service.yml
            - k8s/redis-cluster-ip-service.yml
            - k8s/postgres-cluster-ip-service.yml